// Generated by https://quicktype.io

export interface Student {
  id:         number;
  firstName:  string;
  lastName:   string;
  dob:        Date;
  courses:    Course[];
}

export interface Course {
  id:               number;
  userID:           number;
  createdBy:        string;
  createdAt:        Date;
  updatedBy:        string;
  updatedAt:        Date;
  deletedBy:        string;
  deleteteAt:       Date;
  isDeleted:        boolean;
  name:             string;
  shortDescription: string;
  description:      string;
  publicGoal:       string;
  levels:           number;
  categories:       Chapter[];
  chapter:          Chapter;
  students:         string[];
}

export interface Chapter {
  id:         number;
  userID:     number;
  createdBy:  string;
  createdAt:  Date;
  updatedBy:  string;
  updatedAt:  Date;
  deletedBy:  string;
  deleteteAt: Date;
  isDeleted:  boolean;
  name?:      string;
  courses?:   string[];
  courseId?:  number;
  course?:    string;
  list?:      string;
}
